#ifndef BORROW_MANAGEMENT_GUARD__H 
#define BORROW_MANAGEMENT_GUARD__H

#include <stdio.h>
#include<stdlib.h>
#include<string.h>
/*You can extend the structs (Book and BookArray) defined in this head file;
However, you may not change the function prototypes.
You are also free to add additional head files and data structures as needed.
*/


typedef struct _Borrow {
	char* username;
	unsigned int id; //Book ID
	unsigned int year; //borrow date
	unsigned int mounth; //borrow date
	unsigned int day; //borrow day
	struct _Borrow* next;//point to the next node
}Borrow;

typedef struct _BorrowLink {
	Borrow* head; 
}BorrowLink;

extern BorrowLink borrowList;
//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_borrow(FILE *file);
//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_borrow(FILE *file);

//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_borrow(Borrow borrow);

//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_borrow(Borrow borrow);

#endif
