#ifndef USER_MANAGEMENT_GUARD__H 
#define USER_MANAGEMENT_GUARD__H

#include <stdio.h>
#include<string.h>
#include<stdlib.h>
/*You can extend the structs (Book and BookArray) defined in this head file;
However, you may not change the function prototypes.
You are also free to add additional head files and data structures as needed.
*/


typedef struct _User {
	char *usercount; 
	char* password; 
	struct _User* next;
}User;

typedef struct _UserLink{
	User* head;
}UserLink;

extern UserLink userList;
//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_user(FILE *file);
//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_user(FILE *file);

//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_user(User user);

#endif
